name: Setup node.js
description: 'Set up your GitHub Actions workflow with a specific version of node.js'
inputs:
  node-version:
    description: 'The node.js version to use'
    required: false
    default: '22.14.0'
runs:
  using: "composite"
  steps:
    - name: Test Action
      run: node ./test.js
